
import React from 'react';
import { Bot, FileText, Shuffle, PiggyBank, Target, Shield, TrendingUp, Gem, Code, Globe, Cuboid, Home, Palette, Percent, Rocket, Briefcase, Calculator, Scroll, Building, Landmark, Link, Users, Megaphone, Network, ShoppingBag, User, FileCog, Settings, Eye, CreditCard, Lock, Leaf, Activity, Cpu, AlertTriangle, Gift, Layers, Zap, Database, Server, Clipboard, Atom, Repeat, DollarSign, Sparkles, Terminal, BarChart2, PieChart, Box as BoxIcon, LifeBuoy, Grid, CheckCircle, Scale, LayoutDashboard, Mic, Book, Library } from 'lucide-react';
import { View } from './types';


export const banks = [
    { name: 'Chase', logo: <Building className="w-6 h-6 text-blue-600" />, institution_id: 'ins_1' },
    { name: 'Bank of America', logo: <Landmark className="w-6 h-6 text-red-600" />, institution_id: 'ins_2' },
    { name: 'Wells Fargo', logo: <Shield className="w-6 h-6 text-yellow-600" />, institution_id: 'ins_3' },
    { name: 'Citi', logo: <Globe className="w-6 h-6 text-blue-400" />, institution_id: 'ins_4' },
    { name: 'Capital One', logo: <CreditCard className="w-6 h-6 text-blue-800" />, institution_id: 'ins_5' },
];

export const NAV_ITEMS = [
    {
        group: 'Intelligence Command',
        items: [
            { view: View.Dashboard, title: 'Foundation Dashboard', icon: Bot },
            { view: View.Transactions, title: 'FlowMatrix (Transactions)', icon: FileText },
            { view: View.SendMoney, title: 'Quantum Pay', icon: Shuffle },
            { view: View.Budgets, title: 'Capital Allocation', icon: PiggyBank },
            { view: View.FinancialGoals, title: 'Strategic Goals', icon: Target },
            { view: View.CreditHealth, title: 'Credit Resonance', icon: Shield },
            { view: View.Personalization, title: 'Interface Will', icon: Settings },
            { view: View.Accounts, title: 'Accounts Overview', icon: Briefcase },
        ]
    },
    {
        group: 'The 527 Protocol',
        items: [
            { view: View.TheBook, title: 'The Blueprint (527 Pages)', icon: Book },
            { view: View.KnowledgeBase, title: 'The Academy', icon: Library },
        ]
    },
    {
        group: 'Infinite Wealth',
        items: [
            { view: View.Investments, title: 'Portfolio Overview', icon: TrendingUp },
            { view: View.Crypto, title: 'Web3 & Crypto', icon: Gem },
            { view: View.AlgoTradingLab, title: 'Algo-Trading Lab', icon: Code },
            { view: View.ForexArena, title: 'Forex Arena', icon: Globe },
            { view: View.CommoditiesExchange, title: 'Commodities', icon: Cuboid },
            { view: View.RealEstateEmpire, title: 'Real Estate', icon: Home },
            { view: View.ArtCollectibles, title: 'Art & Collectibles', icon: Palette },
            { view: View.DerivativesDesk, title: 'Derivatives', icon: Percent },
            { view: View.VentureCapital, title: 'Venture Capital', icon: Rocket },
            { view: View.PrivateEquity, title: 'Private Equity', icon: Briefcase },
            { view: View.TaxOptimization, title: 'Civic Contribution', icon: Calculator },
            { view: View.LegacyBuilder, title: 'Legacy Architect', icon: Scroll },
            { view: View.SovereignWealth, title: 'Wealth Simulation', icon: Landmark },
            { view: View.QuantumAssets, title: 'Quantum Assets', icon: Atom },
        ]
    },
    {
        group: 'Citi Connect Core',
        items: [
            { view: View.CitibankAccounts, title: 'Citi Accounts', icon: Building },
            { view: View.CitibankAccountProxy, title: 'Account Proxy', icon: Shuffle },
            { view: View.CitibankBillPay, title: 'Bill Payment', icon: FileText },
            { view: View.CitibankCrossBorder, title: 'Cross Border', icon: Globe },
            { view: View.CitibankPayeeManagement, title: 'Payee Mgmt', icon: Users },
            { view: View.CitibankStandingInstructions, title: 'Standing Instructions', icon: Repeat },
            { view: View.CitibankDeveloperTools, title: 'Citi Dev Tools', icon: Code },
            { view: View.CitibankEligibility, title: 'Eligibility Check', icon: CheckCircle },
            { view: View.CitibankUnmaskedData, title: 'Secure Data View', icon: Eye },
        ]
    },
    {
        group: 'Plaid Nexus',
        items: [
            { view: View.PlaidMainDashboard, title: 'Plaid Overview', icon: Activity },
            { view: View.PlaidIdentity, title: 'Identity Verification', icon: User },
            { view: View.PlaidCRAMonitoring, title: 'CRA Monitoring', icon: Eye },
            { view: View.PlaidInstitutions, title: 'Institutions Explorer', icon: Building },
            { view: View.PlaidItemManagement, title: 'Item Management', icon: Settings },
        ]
    },
    {
        group: 'Enterprise Operations',
        items: [
            { view: View.CorporateCommand, title: 'Corporate Command', icon: Building },
            { view: View.ModernTreasury, title: 'Modern Treasury', icon: Landmark },
            { view: View.Treasury, title: 'Treasury & Capital', icon: DollarSign },
            { view: View.CardPrograms, title: 'Marqeta Cards', icon: CreditCard },
            { view: View.Payments, title: 'Stripe Payments', icon: Zap },
            { view: View.StripeNexus, title: 'Stripe Nexus', icon: Link },
            { view: View.CounterpartyDashboard, title: 'Counterparties', icon: Users },
            { view: View.VirtualAccounts, title: 'Virtual Accounts', icon: Layers },
            { view: View.CorporateActions, title: 'Corporate Actions', icon: FileText },
            { view: View.CreditNoteLedger, title: 'Credit Notes', icon: FileText },
            { view: View.ReconciliationHub, title: 'Reconciliation Hub', icon: Shuffle },
            { view: View.GEINDashboard, title: 'GEIN Dashboard', icon: Network },
            { view: View.CardholderManagement, title: 'Cardholder Mgmt', icon: User },
             { view: View.VentureCapitalDeskView, title: 'VC Desk View', icon: Rocket },
        ]
    },
    {
        group: 'System & Intelligence',
        items: [
            { view: View.AIAdvisor, title: 'AI Advisor', icon: Bot },
            { view: View.AIInsights, title: 'Predictive Insights', icon: Sparkles },
            { view: View.QuantumWeaver, title: 'Quantum Weaver', icon: Network },
            { view: View.AgentMarketplace, title: 'Agent Marketplace', icon: ShoppingBag },
            { view: View.AIAdStudio, title: 'AI Ad Studio', icon: Megaphone },
            { view: View.GlobalPositionMap, title: 'Global Position Map', icon: Globe },
            { view: View.GlobalSsiHub, title: 'Global SSI Hub', icon: Database },
            { view: View.SecurityCompliance, title: 'Security & Compliance', icon: Shield },
            { view: View.DeveloperHub, title: 'Developer Hub', icon: Code },
            { view: View.SchemaExplorer, title: 'ISO 20022 Explorer', icon: FileCog },
            { view: View.ResourceGraph, title: 'Resource Graph', icon: Network },
            { view: View.TheVision, title: 'The Vision', icon: Eye },
            { view: View.ApiPlayground, title: 'API Playground', icon: Terminal },
            { view: View.ComplianceOracle, title: 'Compliance Oracle', icon: Scale },
        ]
    },
    {
        group: 'Admin & Tools',
        items: [
            { view: View.CustomerDashboard, title: 'Customer Dashboard', icon: Users },
            { view: View.VerificationReports, title: 'Verification Reports', icon: Clipboard },
            { view: View.FinancialReporting, title: 'Financial Reporting', icon: BarChart2 },
             { view: View.StripeNexusDashboard, title: 'Stripe Nexus Admin', icon: LayoutDashboard },
        ]
    },
    {
        group: 'All Components',
        items: [
            { view: View.AccountDetails, title: 'Account Details', icon: FileText },
            { view: View.AccountList, title: 'Account List', icon: FileText },
            { view: View.AccountStatementGrid, title: 'Account Statement Grid', icon: Grid },
            { view: View.AccountsView, title: 'Accounts View', icon: Briefcase },
            { view: View.AccountVerificationModal, title: 'Acct Verification Modal', icon: Shield },
            { view: View.ACHDetailsDisplay, title: 'ACH Details Display', icon: FileText },
            { view: View.AICommandLog, title: 'AI Command Log', icon: Terminal },
            { view: View.AIPredictionWidget, title: 'AI Prediction Widget', icon: Sparkles },
            { view: View.AssetCatalog, title: 'Asset Catalog', icon: BoxIcon },
            { view: View.AutomatedSweepRules, title: 'Automated Sweep Rules', icon: Repeat },
            { view: View.BalanceReportChart, title: 'Balance Report Chart', icon: BarChart2 },
            { view: View.BalanceTransactionTable, title: 'Balance Txn Table', icon: FileText },
            { view: View.CardDesignVisualizer, title: 'Card Design Visualizer', icon: Palette },
            { view: View.ChargeDetailModal, title: 'Charge Detail Modal', icon: FileText },
            { view: View.ChargeList, title: 'Charge List', icon: FileText },
            { view: View.ConductorConfigurationView, title: 'Conductor Config', icon: Settings },
            { view: View.CounterpartyDetails, title: 'Counterparty Details', icon: User },
            { view: View.CounterpartyForm, title: 'Counterparty Form', icon: FileCog },
            { view: View.DisruptionIndexMeter, title: 'Disruption Index Meter', icon: Activity },
            { view: View.DocumentUploader, title: 'Document Uploader', icon: FileCog },
            { view: View.DownloadLink, title: 'Download Link', icon: Link },
            { view: View.EarlyFraudWarningFeed, title: 'Fraud Warning Feed', icon: AlertTriangle },
            { view: View.ElectionChoiceForm, title: 'Election Choice Form', icon: FileCog },
            { view: View.EventNotificationCard, title: 'Event Notification Card', icon: Megaphone },
            { view: View.ExpectedPaymentsTable, title: 'Expected Payments Table', icon: FileText },
            { view: View.ExternalAccountCard, title: 'External Account Card', icon: CreditCard },
            { view: View.ExternalAccountForm, title: 'External Account Form', icon: FileCog },
            { view: View.ExternalAccountsTable, title: 'External Accounts Table', icon: FileText },
            { view: View.FinancialAccountCard, title: 'Financial Account Card', icon: CreditCard },
            { view: View.IncomingPaymentDetailList, title: 'Incoming Pmt Detail', icon: FileText },
            { view: View.InvoiceFinancingRequest, title: 'Invoice Financing Req', icon: FileCog },
            { view: View.PaymentInitiationForm, title: 'Payment Initiation Form', icon: FileCog },
            { view: View.PaymentMethodDetails, title: 'Pmt Method Details', icon: FileText },
            { view: View.PaymentOrderForm, title: 'Payment Order Form', icon: FileCog },
            { view: View.PayoutsDashboard, title: 'Payouts Dashboard', icon: DollarSign },
            { view: View.PnLChart, title: 'PnL Chart', icon: PieChart },
            { view: View.RefundForm, title: 'Refund Form', icon: FileCog },
            { view: View.RemittanceInfoEditor, title: 'Remittance Info Editor', icon: FileCog },
            { view: View.ReportingView, title: 'Reporting View', icon: BarChart2 },
            { view: View.ReportRunGenerator, title: 'Report Run Generator', icon: FileCog },
            { view: View.ReportStatusIndicator, title: 'Report Status Indicator', icon: Activity },
            { view: View.SsiEditorForm, title: 'SSI Editor Form', icon: FileCog },
            { view: View.StripeNexusView, title: 'Stripe Nexus View', icon: Link },
            { view: View.StripeStatusBadge, title: 'Stripe Status Badge', icon: Shield },
            { view: View.StructuredPurposeInput, title: 'Structured Purpose Input', icon: FileCog },
            { view: View.SubscriptionList, title: 'Subscription List', icon: FileText },
            { view: View.TimeSeriesChart, title: 'Time Series Chart', icon: BarChart2 },
            { view: View.TradeConfirmationModal, title: 'Trade Confirm Modal', icon: FileText },
            { view: View.TransactionFilter, title: 'Transaction Filter', icon: FileCog },
            { view: View.TransactionList, title: 'Transaction List', icon: FileText },
            { view: View.TreasuryTransactionList, title: 'Treasury Txn List', icon: FileText },
            { view: View.UniversalObjectInspector, title: 'Object Inspector', icon: Eye },
            { view: View.VirtualAccountForm, title: 'Virtual Acct Form', icon: FileCog },
            { view: View.VirtualAccountsTable, title: 'Virtual Accts Table', icon: FileText },
            { view: View.VoiceControl, title: 'Voice Control', icon: Mic },
            { view: View.WebhookSimulator, title: 'Webhook Simulator', icon: Terminal },
        ]
    }
];

export const AppTheme = {
    colors: {
        primary: {
            DEFAULT: '#06b6d4',
            light: '#67e8f9',
            dark: '#0e7490',
        },
        secondary: {
            DEFAULT: '#6366f1',
            light: '#a5b4fc',
            dark: '#4338ca',
        },
        background: {
            main: '#111827',
            card: 'rgba(31, 41, 55, 0.5)',
            interactive: '#374151',
        },
        text: {
            main: '#f9fafb',
            headings: '#ffffff',
            muted: '#9ca3af',
            accent: '#e5e7eb',
        },
        status: {
            success: '#22c55e',
            warning: '#f59e0b',
            error: '#ef4444',
            info: '#3b82f6',
        },
        border: {
            DEFAULT: 'rgba(75, 85, 99, 0.6)',
            interactive: 'rgba(6, 182, 212, 0.5)',
        },
    },
};


// --- CONSOLIDATED FROM: ./constants.tsx ---

import React from 'react';
import { View, Feature, ExternalApp } from './types';
import { 
  Layout, BrainCircuit, EyeOff, Sparkles, Mic, ShieldCheck, 
  Fingerprint, Database, TrendingUp, Command, Landmark,
  Settings, DatabaseZap, Megaphone, LifeBuoy, 
  ShieldAlert, Network, Cpu, Key, Rocket, Send,
  Zap, Hammer, Puzzle, Globe, Target, Box, Binary, Shield, Compass, Briefcase, Activity, Headphones, BarChart3, Lock, Users, Server, Award, FileCode, FolderTree, BookOpen
} from 'lucide-react';

export interface NavSection {
  label: string;
  items: { id: string; label: string; icon: React.ReactNode }[];
}

export const NAV_SECTORS: NavSection[] = [
    {
        label: 'Sovereign Archives & Files',
        items: [
            { id: View.FilesVault, label: 'Files & Dossier Vault', icon: <FolderTree size={18} className="text-amber-400" /> },
            { id: View.WorkspaceNexus, label: 'Workspace Nexus (Drive)', icon: <Globe size={18} className="text-cyan-400" /> },
        ]
    },
    {
        label: 'Command',
        items: [
            { id: View.Dashboard, label: 'Sovereign Bridge', icon: <Layout size={18} /> },
            { id: View.CryptoVerifier, label: 'JWE / JWS Verifier', icon: <ShieldCheck size={18} className="text-emerald-400" /> },
            { id: View.BillingIdentity, label: 'Identity Vault', icon: <Lock size={18} className="text-indigo-400" /> },
            { id: View.PortalHub, label: 'Portal Constellation', icon: <Box size={18} className="text-yellow-400" /> },
            { id: View.DataIngest, label: 'Neural Ingest', icon: <DatabaseZap size={18} className="text-orange-400" /> },
            { id: View.AzureApps, label: 'Azure Directory', icon: <Server size={18} className="text-blue-400" /> },
            { id: View.FloridaVoter, label: 'FL 2026 Voter Registration', icon: <Award size={18} className="text-lime-400" /> },
        ]
    },
    {
        label: 'The Legions',
        items: [
            { id: View.LegionArchitect, label: 'L-I: Architect', icon: <BrainCircuit size={18} className="text-lime-400" /> },
            { id: View.LegionGhost, label: 'L-II: Ghost', icon: <EyeOff size={18} className="text-purple-400" /> },
            { id: View.LegionVisualizer, label: 'L-III: Visualizer', icon: <Sparkles size={18} className="text-pink-400" /> },
            { id: View.LegionVoice, label: 'L-IV: Voice', icon: <Mic size={18} className="text-emerald-400" /> },
            { id: View.LegionAuditor, label: 'L-V: Auditor', icon: <ShieldCheck size={18} className="text-blue-400" /> },
            { id: View.LegionLive, label: 'L-VI: Live Communion', icon: <Headphones size={18} className="text-cyan-400" /> },
        ]
    },
    {
        label: 'Sovereignty Core',
        items: [
            { id: View.IdentityCitadel, label: 'ID Citadel', icon: <Fingerprint size={18} className="text-teal-400" /> },
            { id: View.RecoveryMesh, label: 'Recovery Mesh', icon: <LifeBuoy size={18} className="text-orange-400" /> },
            { id: View.PrivacyGuardian, label: 'Privacy Blinder', icon: <Shield size={18} className="text-indigo-400" /> },
            { id: View.TrustRegistry, label: 'Trust Registry', icon: <Network size={18} className="text-blue-400" /> },
        ]
    },
    {
        label: 'Asset Forge',
        items: [
            { id: View.WealthNexus, label: 'Capital Nexus', icon: <TrendingUp size={18} className="text-green-400" /> },
            { id: View.TokenIssuance, label: 'Asset Forge', icon: <Binary size={18} className="text-yellow-400" /> },
            { id: View.MarketingAutomation, label: 'Growth Hub', icon: <Megaphone size={18} className="text-pink-400" /> },
        ]
    },
    {
        label: 'Intelligence',
        items: [
            { id: View.SovereignIntelligence, label: 'Sovereign Intelligence', icon: <ShieldAlert size={18} className="text-red-500" /> },
            { id: View.UniverseGraph, label: 'Universe Graph 3D', icon: <Network size={18} className="text-purple-400" /> },
            { id: View.AriaComms, label: 'Aria Neural Comms', icon: <Headphones size={18} className="text-pink-400" /> },
            { id: View.IntelligenceHub, label: 'Intelligence Core', icon: <Cpu size={18} className="text-cyan-400" /> },
            { id: View.NeuralTools, label: 'Neural Tools', icon: <Zap size={18} className="text-yellow-400" /> },
            { id: View.NexusBuilder, label: 'Nexus Forge', icon: <Hammer size={18} className="text-gray-400" /> },
        ]
    },
    {
        label: 'Governance & Audits',
        items: [
            { id: View.ImpeachmentGenerator, label: 'Impeachment Audit', icon: <ShieldAlert size={18} className="text-amber-400" /> },
            { id: View.ContractorLobbying, label: 'Contractor Lobbying ROI', icon: <BarChart3 size={18} className="text-lime-400" /> },
            { id: View.SentryEngine, label: 'ISO20022 Sentry Engine', icon: <Lock size={18} className="text-cyan-400" /> },
        ]
    },
    {
        label: 'Citi Treasury & Alpaca Suite',
        items: [
            { id: View.AlpacaTqqq, label: 'TQQQ Quantitative Trade', icon: <TrendingUp size={18} className="text-emerald-400" /> },
            { id: View.SovereignMarketTakeover, label: 'Market Takeover Hub', icon: <Globe size={18} className="text-yellow-400" /> },
            { id: View.PlaidAlpacaBridge, label: 'Plaid-Alpaca Bridge', icon: <Zap size={18} className="text-emerald-400" /> },
            { id: View.StripeAlpacaBridge, label: 'Stripe-Alpaca Bridge', icon: <Send size={18} className="text-indigo-400" /> },
            { id: View.CitiAlpacaBridge, label: 'Citi-Alpaca Bridge', icon: <Landmark size={18} className="text-cyan-400" /> },
            { id: View.AlpacaBroker, label: 'Alpaca Broker API Suite', icon: <TrendingUp size={18} className="text-yellow-400" /> },
            { id: View.AlpacaAccounts, label: 'Alpaca Account & KYC', icon: <Shield size={18} className="text-yellow-400" /> },
            { id: View.AlpacaTrading, label: 'Alpaca Trading Terminal', icon: <TrendingUp size={18} className="text-emerald-400" /> },
            { id: View.AlpacaFunding, label: 'Alpaca Funding Hub', icon: <Landmark size={18} className="text-cyan-400" /> },
            { id: View.AlpacaJournals, label: 'Alpaca Sovereign Journals', icon: <Activity size={18} className="text-yellow-400" /> },
            { id: View.AlpacaRebalancing, label: 'Alpaca Rebalancing Engine', icon: <Activity size={18} className="text-purple-400" /> },
            { id: View.AlpacaTokenization, label: 'Alpaca RWA Tokenization', icon: <Shield size={18} className="text-pink-400" /> },
            { id: View.AlpacaIpoMarketplace, label: 'Alpaca IPO Marketplace', icon: <Rocket size={18} className="text-amber-400" /> },
            { id: View.AlpacaCryptoWallets, label: 'Alpaca Crypto Wallets', icon: <Lock size={18} className="text-purple-400" /> },
            { id: View.AlpacaReporting, label: 'Alpaca EOD Reporting', icon: <Activity size={18} className="text-emerald-400" /> },
            { id: View.ModernTreasuryLedger, label: 'Modern Treasury Ledger', icon: <Landmark size={18} className="text-cyan-400" /> },
            { id: View.CitiUkInternationalPayments, label: 'Citi UK International Payments', icon: <Send size={18} className="text-emerald-400" /> },
            { id: View.FapiPipeline, label: 'FAPI 2.0 Security Pipeline', icon: <Shield size={18} className="text-emerald-400" /> },
            { id: View.CitiConnectInitiation, label: 'Payment Initiation', icon: <Rocket size={18} className="text-emerald-400" /> },
            { id: View.CitiConnectInquiry, label: 'Status Inquiry', icon: <Activity size={18} className="text-blue-400" /> },
            { id: View.CitiConnectNotifications, label: 'Push Alerts', icon: <Megaphone size={18} className="text-pink-400" /> },
            { id: View.CitiTreasury, label: 'Treasury Command', icon: <Landmark size={18} className="text-amber-400" /> },
            { id: View.CitiPartnerHub, label: 'Citi Partner API Transactions', icon: <Landmark size={18} className="text-cyan-400" /> },
        ]
    },
    {
        label: 'Sovereign Modules',
        items: [
            { id: 'administration-audit', label: 'Administration Audit', icon: <ShieldCheck size={18} className="text-amber-400" /> },
            { id: 'ai-ad-studio', label: 'AI Ad Studio', icon: <Sparkles size={18} className="text-pink-400" /> },
            { id: 'ai-advisor', label: 'AI Advisor', icon: <BrainCircuit size={18} className="text-lime-400" /> },
            { id: 'ai-insights', label: 'AI Insights', icon: <Sparkles size={18} className="text-cyan-400" /> },
            { id: 'btc-swing-trading', label: 'BTC Swing Trading', icon: <TrendingUp size={18} className="text-emerald-400" /> },
            { id: 'citi-alpaca-bridge-view', label: 'Citi-Alpaca Bridge View', icon: <Zap size={18} className="text-yellow-400" /> },
            { id: 'plaid-alpaca-bridge-view', label: 'Plaid-Alpaca Bridge View', icon: <Zap size={18} className="text-emerald-400" /> },
            { id: 'real-estate-alpaca-bridge', label: 'Real Estate Alpaca Bridge', icon: <Briefcase size={18} className="text-indigo-400" /> },
            { id: 'sovereign-market-takeover-dashboard', label: 'Market Takeover Dashboard', icon: <Globe size={18} className="text-red-400" /> },
            { id: 'stripe-alpaca-bridge-view', label: 'Stripe-Alpaca Bridge View', icon: <Send size={18} className="text-blue-400" /> },
            { id: 'tax-lien-modern-treasury-bridge', label: 'Tax Lien MT Bridge', icon: <Landmark size={18} className="text-purple-400" /> },
            { id: 'card-customization', label: 'Card Customization', icon: <Settings size={18} className="text-gray-400" /> },
            { id: 'card', label: 'Sovereign Card', icon: <Shield size={18} className="text-cyan-400" /> },
            { id: 'citi-decryption', label: 'Citi Decryption Utility', icon: <Lock size={18} className="text-red-400" /> },
            { id: 'citi-sovereign-ledger', label: 'Citi Sovereign Ledger', icon: <Database size={18} className="text-blue-400" /> },
            { id: 'corporate-command', label: 'Corporate Command', icon: <Command size={18} className="text-indigo-400" /> },
            { id: 'credit-health', label: 'Credit Health', icon: <Activity size={18} className="text-emerald-400" /> },
            { id: 'developer', label: 'Developer View', icon: <Settings size={18} className="text-gray-400" /> },
            { id: 'entra-swarm', label: 'Entra Swarm Manager', icon: <Users size={18} className="text-blue-400" /> },
            { id: 'feature-palette', label: 'Feature Palette', icon: <Layout size={18} className="text-pink-400" /> },
            { id: 'financial-democracy', label: 'Financial Democracy', icon: <Landmark size={18} className="text-yellow-400" /> },
            { id: 'financial-goals', label: 'Financial Goals', icon: <Target size={18} className="text-lime-400" /> },
            { id: 'gas-price-correlation', label: 'Gas Price Correlation', icon: <Activity size={18} className="text-orange-400" /> },
            { id: 'gemini-key-modal', label: 'Gemini Key Modal', icon: <Key size={18} className="text-yellow-400" /> },
            { id: 'gis-property-map', label: 'GIS Property Map', icon: <Globe size={18} className="text-green-400" /> },
            { id: 'government-api-dashboard', label: 'Government API Dashboard', icon: <Layout size={18} className="text-blue-400" /> },
            { id: 'irs-tax-filing', label: 'IRS Tax Filing', icon: <FileCode size={18} className="text-red-400" /> },
            { id: 'sec-filing-viewer', label: 'SEC Filing Viewer', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'hok-token-mint', label: 'HoK Token Mint', icon: <Binary size={18} className="text-yellow-400" /> },
            { id: 'impact-tracker', label: 'Impact Tracker', icon: <Activity size={18} className="text-green-400" /> },
            { id: 'injustice-dashboard', label: 'Injustice Dashboard', icon: <ShieldAlert size={18} className="text-red-500" /> },
            { id: 'krypto-bridge', label: 'Krypto Bridge Widget', icon: <Zap size={18} className="text-purple-400" /> },
            { id: 'machine-view', label: 'Machine View', icon: <Cpu size={18} className="text-gray-400" /> },
            { id: 'marketplace', label: 'Marketplace', icon: <Box size={18} className="text-yellow-400" /> },
            { id: 'nfc-validator', label: 'NFC Validator', icon: <Fingerprint size={18} className="text-teal-400" /> },
            { id: 'ofx-statement-viewer', label: 'OFX Statement Viewer', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'open-banking', label: 'Open Banking View', icon: <Landmark size={18} className="text-blue-400" /> },
            { id: 'personalization', label: 'Personalization', icon: <Settings size={18} className="text-gray-400" /> },
            { id: 'political-compliance', label: 'Political Compliance', icon: <ShieldCheck size={18} className="text-amber-400" /> },
            { id: 'public-aid-calculator', label: 'Public Aid Calculator', icon: <BarChart3 size={18} className="text-lime-400" /> },
            { id: 'deed-registrar', label: 'Deed Registrar', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'escrow-manager', label: 'Escrow Manager', icon: <Lock size={18} className="text-indigo-400" /> },
            { id: 'property-marketplace', label: 'Property Marketplace', icon: <Box size={18} className="text-yellow-400" /> },
            { id: 'recent-transactions', label: 'Recent Transactions', icon: <Activity size={18} className="text-emerald-400" /> },
            { id: 'security-orchestrator', label: 'Security Orchestrator', icon: <Shield size={18} className="text-red-500" /> },
            { id: 'security-view', label: 'Security View', icon: <ShieldCheck size={18} className="text-blue-400" /> },
            { id: 'sovereign-chat', label: 'Sovereign Chat', icon: <Headphones size={18} className="text-pink-400" /> },
            { id: 'sovereign-dashboard', label: 'Sovereign Dashboard', icon: <Layout size={18} className="text-cyan-400" /> },
            { id: 'sovereign-deal-audit', label: 'Sovereign Deal Audit', icon: <ShieldCheck size={18} className="text-amber-400" /> },
            { id: 'story-viewer', label: 'Story Viewer', icon: <Compass size={18} className="text-lime-400" /> },
            { id: 'foreclosure-tracker', label: 'Foreclosure Tracker', icon: <Activity size={18} className="text-red-400" /> },
            { id: 'tax-lien-auctions', label: 'Tax Lien Auctions', icon: <Landmark size={18} className="text-purple-400" /> },
            { id: 'universe-3d', label: 'Universe 3D', icon: <Network size={18} className="text-purple-400" /> },
            { id: 'voice-control', label: 'Voice Control', icon: <Mic size={18} className="text-emerald-400" /> },
            { id: 'wallet-connect-modal', label: 'Wallet Connect Modal', icon: <Lock size={18} className="text-indigo-400" /> },
            { id: 'war-appropriations-tracker', label: 'War Appropriations Tracker', icon: <BarChart3 size={18} className="text-red-500" /> },
            { id: 'wealth-distribution-chart', label: 'Wealth Distribution Chart', icon: <BarChart3 size={18} className="text-green-400" /> },
            { id: 'wealth-timeline', label: 'Wealth Timeline', icon: <Activity size={18} className="text-yellow-400" /> },
            { id: 'balance-summary', label: 'Balance Summary', icon: <Layout size={18} className="text-cyan-400" /> },
            { id: 'plaid-link', label: 'Plaid Link', icon: <Zap size={18} className="text-emerald-400" /> },
            { id: 'api-integration', label: 'API Integration', icon: <Settings size={18} className="text-gray-400" /> },
            { id: 'dashboard-view', label: 'Dashboard View', icon: <Layout size={18} className="text-blue-400" /> },
            { id: 'investments-portfolio', label: 'Investments Portfolio', icon: <TrendingUp size={18} className="text-emerald-400" /> },
            { id: 'flow-controller', label: 'Flow Controller', icon: <Activity size={18} className="text-purple-400" /> },
            { id: 'growth-nexus', label: 'Growth Nexus', icon: <Network size={18} className="text-pink-400" /> },
            { id: 'griffin-mcp', label: 'Griffin MCP Server', icon: <Server size={18} className="text-cyan-400" /> },
        ]
    },
    {
        label: 'Operations',
        items: [
            { id: View.CitiGateway, label: 'Citi Sovereign Gateway', icon: <Landmark size={18} className="text-blue-400" /> },
            { id: View.WorkspaceNexus, label: 'Workspace Nexus', icon: <Globe size={18} className="text-blue-400" /> },
            { id: View.GcpInventory, label: 'Cloud Infrastructure', icon: <DatabaseZap size={18} className="text-orange-300" /> },
            { id: View.InstitutionalHub, label: 'Institutional Hub', icon: <Command size={18} className="text-cyan-400" /> },
            { id: View.GlobalLedger, label: 'Global Ledger', icon: <Database size={18} /> },
            { id: View.AstraDBQuickstart, label: 'Astra DB Quickstart', icon: <DatabaseZap size={18} className="text-emerald-400" /> },
            { id: View.IntegrationsMarketplace, label: 'Integrations', icon: <Puzzle size={18} className="text-purple-400" /> },
        ]
    },
    {
        label: 'Applications',
        items: [
            { id: 'app-github_audit_sync_agent', label: 'Github Audit Sync Agent', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-b2b_routing_number_resolver', label: 'B2B Routing Number Resolver', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-citi_account_excel_parser', label: 'Citi Account Excel Parser', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-balance_transfer_analytics_dashboard', label: 'Balance Transfer Analytics', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-card_lifecycle_compliance_checker', label: 'Card Lifecycle Compliance', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-broker_compliance_trade_auditor', label: 'Broker Compliance Trade Auditor', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-military_fund_allocator', label: 'Military Fund Allocator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-camt053_statement_parser', label: 'CAMT053 Statement Parser', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-camt053_balance_reconciler', label: 'CAMT053 Balance Reconciler', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-b2b_cash_flow_stress_tester', label: 'B2B Cash Flow Stress Tester', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-balance_transfer_compliance_auditor', label: 'Balance Transfer Compliance Auditor', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-card_spend_limit_manager', label: 'Card Spend Limit Manager', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-financial_regulatory_guardrail', label: 'Financial Regulatory Guardrail', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-citi_account_kyc_risk_profiler', label: 'Citi Account KYC Risk Profiler', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-statement_reconciliation_portal', label: 'Statement Reconciliation Portal', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-citi_account_anomaly_detector', label: 'Citi Account Anomaly Detector', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-card_listing_mock_server', label: 'Card Listing Mock Server', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-multi_currency_balance_consolidator', label: 'Multi Currency Balance Consolidator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-card_pin_hasher_validator', label: 'Card PIN Hasher Validator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-b2b_audit_trail_generator', label: 'B2B Audit Trail Generator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-credit_limit_utilization_monitor', label: 'Credit Limit Utilization Monitor', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-financial_statement_verifier', label: 'Financial Statement Verifier', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-card_outstanding_balance_tracker', label: 'Card Outstanding Balance Tracker', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-broker_order_execution_simulator', label: 'Broker Order Execution Simulator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-pqc_crypto_bridge_simulator', label: 'PQC Crypto Bridge Simulator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-election_integrity_dashboard', label: 'Election Integrity Dashboard', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-balance_transfer_disbursement_orchestrator', label: 'Balance Transfer Disbursement Orchestrator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-cvv_decryption_mock_service', label: 'CVV Decryption Mock Service', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-balance_transfer_interest_simulator', label: 'Balance Transfer Interest Simulator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-camt053_mock_generator', label: 'CAMT053 Mock Generator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-schema_catalog_custom_registry', label: 'Schema Catalog Custom Registry', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-credit_card_simulator', label: 'Credit Card Simulator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-card_tokenization_service', label: 'Card Tokenization Service', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-schema_conformance_audit_tool', label: 'Schema Conformance Audit Tool', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-voter_registration_portal', label: 'Voter Registration Portal', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-camt053_transaction_exporter', label: 'CAMT053 Transaction Exporter', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-service_principal_provisioner', label: 'Service Principal Provisioner', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-schema_catalog_search_engine', label: 'Schema Catalog Search Engine', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-account_summary_mock_service', label: 'Account Summary Mock Service', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-azure_ad_app_auditor', label: 'Azure AD App Auditor', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-schema_validator_orchestrator', label: 'Schema Validator Orchestrator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-cross_cloud_federation_manager', label: 'Cross Cloud Federation Manager', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-card_function_access_controller', label: 'Card Function Access Controller', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-api_response_conformance_validator', label: 'API Response Conformance Validator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-balance_transfer_batch_scheduler', label: 'Balance Transfer Batch Scheduler', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-balance_transfer_calculator', label: 'Balance Transfer Calculator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-card_test_suite_conformance_analyzer', label: 'Card Test Suite Conformance Analyzer', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-api_test_runner', label: 'API Test Runner', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-b2b_portfolio_wealth_analyzer', label: 'B2B Portfolio Wealth Analyzer', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-citi_account_interest_accrual_simulator', label: 'Citi Account Interest Accrual Simulator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-b2b_transaction_categorizer', label: 'B2B Transaction Categorizer', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-b2b_routing_decryptor_validator', label: 'B2B Routing Decryptor Validator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-audit_compliance_tracker', label: 'Audit Compliance Tracker', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-fedramp_compliance_monitor', label: 'FedRAMP Compliance Monitor', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-card_merchant_category_classifier', label: 'Card Merchant Category Classifier', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-balance_transfer_lead_generator', label: 'Balance Transfer Lead Generator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-b2b_interest_rate_optimizer', label: 'B2B Interest Rate Optimizer', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-app_consent_analyzer', label: 'App Consent Analyzer', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-b2b_corporate_liquidity_forecaster', label: 'B2B Corporate Liquidity Forecaster', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-card_activation_simulator', label: 'Card Activation Simulator', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-credit_risk_analyzer', label: 'Credit Risk Analyzer', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-balance_transfer_eligibility_checker', label: 'Balance Transfer Eligibility Checker', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-treasury_reconciliation_engine', label: 'Treasury Reconciliation Engine', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-citiconnect_integration_gateway', label: 'CitiConnect Integration Gateway', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-citizenship_verification_gateway', label: 'Citizenship Verification Gateway', icon: <FileCode size={18} className="text-cyan-400" /> },
            { id: 'app-supplementary_card_orchestrator', label: 'Supplementary Card Orchestrator', icon: <FileCode size={18} className="text-cyan-400" /> },
        ]
    },
    {
        label: 'System',
        items: [
            { id: View.Rewards, label: 'Rewards Hub', icon: <Target size={18} className="text-red-400" /> },
            { id: View.TheVision, label: 'The Manifesto', icon: <Compass size={18} className="text-lime-400" /> },
            { id: View.PaymentMethods, label: 'Payment Gateways', icon: <Briefcase size={18} className="text-indigo-400" /> },
            { id: View.Settings, label: 'Core Settings', icon: <Settings size={18} className="text-gray-500" /> },
        ]
    }
];

export const NAV_ITEMS = NAV_SECTORS.flatMap(s => s.items);

export const SOVEREIGN_APPS: ExternalApp[] = [
  { id: 'app-files-vault', name: 'Sovereign Files & Dossier Vault', description: 'Direct access to all Executive Orders, 100-page Story pages, Legislative Bill chapters, and system files.', category: 'Security', viewId: View.FilesVault },
  { id: 'app-01', name: 'Executive Bridge Control', description: 'Primary OS interface for billionaire-tier asset management.', category: 'Security', viewId: View.Dashboard },
  { id: 'app-02', name: "The Sovereign's Ledger", description: 'Atomic-settlement transaction stream for verified architects.', category: 'Banking', viewId: View.GlobalLedger },
  { id: 'app-03', name: 'Intelligence Nexus', description: 'Deep-learning hub for portfolio trajectory and risk vectors.', category: 'AI', viewId: View.IntelligenceHub },
  { id: 'app-04', name: 'Legion I: Architect', description: 'Strategic reasoning engine for high-fidelity venture forge.', category: 'AI', viewId: View.LegionArchitect, isPremium: true },
  { id: 'app-05', name: 'Neural Recovery Mesh', description: 'Shamir-secret-sharing protocol for hardware-bound identity.', category: 'Security', viewId: View.RecoveryMesh },
  { id: 'app-06', name: 'Asset Forge v2.0', description: 'Multi-chain token issuance with AI-driven economic modeling.', category: 'Banking', viewId: View.TokenIssuance },
  { id: 'app-07', name: 'Global Command Integrations', description: 'Connect third-party enterprise meshes to the Sovereign Hub.', category: 'Dev', viewId: View.IntegrationsMarketplace },
  { id: 'app-08', name: 'Legion VI: Live Communion', description: 'Real-time low-latency voice interface with Gemini Core.', category: 'AI', viewId: View.LegionLive },
  { id: 'app-09', name: 'Neural Tools Suite', description: 'Low-level utilities for token estimation and topic distillation.', category: 'Dev', viewId: View.NeuralTools },
  { id: 'app-10', name: 'Identity Citadel', description: 'TEE hardware-bound root of trust for all user interactions.', category: 'Security', viewId: View.IdentityCitadel },
  
  // --- Integrated admin08077 Spaces ---
  { id: "AIBANKINGUNIVERSITY", name: "AI Banking University", description: "Comprehensive syllabus to AI_BANKING_9999 protocols.", category: "AI", isPremium: true },
  { id: "AIBANKINGUNIVERSITY-AI-AGENT-APP", name: "AI Agent App", description: "Specialized agent demonstration for James Burvel O'Callaghan III.", category: "AI", isPremium: true },
  { id: "Aiab", name: "Aiab Finance", description: "Personal finance management via sovereign Demo Bank interface.", category: "Banking" },
  { id: "Aib8nking", name: "Aib8nking", description: "Core finance management and settlement system.", category: "Banking" },
  { id: "Aibankdemo2", name: "Linked Ledger v2", description: "Advanced visualization for multiple linked bank accounts.", category: "Banking" },
  { id: "Aimobile", name: "AI Mobile Architect", description: "Context-aware code suggestions for sovereign mobile development.", category: "Dev" },
  { id: "Bb", name: "Bb Core UI", description: "Foundation UI components for the Demo Bank ecosystem.", category: "Dev" },
  { id: "Githubgemini", name: "GitHub Gemini Node", description: "Autonomous pull, recode, and push logic for neural repos.", category: "Dev", isPremium: true },
  { id: "Jamesocallaghanprivatebank", name: "Private Banking Citadel", description: "High-net-worth specialized banking interface.", category: "Banking", isPremium: true },
  { id: "Jbo3", name: "Jbo3 Data Matrix", description: "High-fidelity financial data visualization engine.", category: "Dev" },
  { id: "Jbo33", name: "Jbo33 Analytics", description: "Deep-learning analytics for market trajectory monitoring.", category: "AI" },
  { id: "NewWa", name: "Neural Markdown", description: "AI-enhanced markdown rendering engine.", category: "Dev" },
  { id: "Worldsfirstautonomousbank", name: "Autonomous Bank Hub", description: "Master configurations for self-governing financial spaces.", category: "Security", isPremium: true },
  { id: "Ai", name: "Core Neural Engine", description: "Base intelligence unit for the Aquarius Singularity.", category: "AI" },
  { id: "Ai-Banking-Sovereign", name: "Sovereign Banking Core", description: "Low-level banking logic for independent financial states.", category: "Security" },
  { id: "Aibankdemo", name: "Classic Banking Portal", description: "Simulated legacy banking interface for compatibility testing.", category: "Banking" },
  { id: "Aibanke", name: "Aibanke Insights", description: "Predictive banking insights and spending analysis.", category: "AI" },
  { id: "Aibankingdemo", name: "Secure Insights Node", description: "Encrypted financial analytics for verified visionary accounts.", category: "Security" },
  { id: "Aibankingthedemo", name: "Rapid Demo Node", description: "High-speed demonstration of AI banking capabilities.", category: "Banking" },
  { id: "Aidev", name: "DevCore AI Toolkit", description: "Neural development utilities for sovereign engineers.", category: "Dev" },
  { id: "Quantum-Code-Architect", name: "Quantum Code Forge", description: "Next-gen code engineering and symbolic reasoning.", category: "Dev", isPremium: true },
  { id: "Aippk", name: "Advanced Neural PPK", description: "Hardware-bound identity and key management.", category: "Security" },
  { id: "Airenderer", name: "AI Document Factory", description: "Markdown to high-fidelity HTML conversion engine.", category: "Dev" },
  { id: "Aitr", name: "Neural Chat Matrix", description: "Advanced conversational interface for AI communion.", category: "AI" },
  { id: "Apiai", name: "API Sovereign Gateway", description: "Centralized control for external neural service links.", category: "Dev" },
  { id: "THEUNORTHODOXCHRONICLESOFKAIANDHIS100ADVERSARIALAIAGENTS", name: "Adversarial Agents Hub", description: "The Unorthodox Chronicles: 100 agent logic simulator.", category: "AI", isPremium: true },
  { id: "Cc", name: "System Command Center", description: "Global monitoring and execution hub.", category: "Security" },
  { id: "Chatbot", name: "Legacy Chat Node", description: "Fallback conversational unit for standard banking queries.", category: "AI" },
  { id: "Chrome-Flags", name: "System Flag Registry", description: "Kernel-level system feature management.", category: "Dev" },
  { id: "Convo", name: "Convo Assistant", description: "Real-time pair-programming and code assistance.", category: "Dev" },
  { id: "D", name: "Aesthetic Gradient Engine", description: "Dynamic color and theme generation based on neural mood.", category: "Dev" },
  { id: "Demob", name: "Demo B Shard", description: "Isolated testing environment for beta banking modules.", category: "Banking" },
  { id: "Demoo", name: "Snippet Repository", description: "Collective intelligence code shard library.", category: "Dev" },
  { id: "Drip-Faucet", name: "Token Drip Faucet", description: "Test token issuance for sovereign DLT networks.", category: "Banking" },
  { id: "Fr", name: "FR Logic Interface", description: "Financial Relationship monitoring and mapping.", category: "Banking" },
  { id: "Genai", name: "Website Materializer", description: "Generative AI engine for rapid website prototyping.", category: "Dev" },
  { id: "Hhh", name: "Personal Wealth Matrix", description: "High-density personal finance tracker.", category: "Banking" },
  { id: "Inventions", name: "Venture Visualizer", description: "3D visualization of capital invention trajectories.", category: "Dev" },
  { id: "James", name: "Brilliance Engine", description: "High-order reasoning and creativity booster.", category: "AI" },
  { id: "Javascript-Python", name: "Polyglot Compiler", description: "Browser-based execution for multi-language shards.", category: "Dev" },
  { id: "Jocall3", name: "Portfolio Oracle", description: "AI-driven optimization for multi-chain asset portfolios.", category: "AI" },
  { id: "Learnhebrew", name: "Linguistic Portal", description: "Language acquisition module for global visionary expansion.", category: "Legacy" },
  { id: "Merrychristmas", name: "Seasonal Logic", description: "Context-aware seasonal UI and greeting protocols.", category: "Legacy" },
  { id: "Model", name: "Model Architecture Hub", description: "Interface for selecting and tuning active AI models.", category: "AI" },
  { id: "Monetize", name: "Yield Mapping Console", description: "Advanced financial metrics for monetization strategy.", category: "Banking" },
  { id: "Multi", name: "Multi-Tool Shard", description: "Versatile utility collection for system maintenance.", category: "Dev" },
  { id: "Mvp", name: "MVP0 Genesis Node", description: "The foundation of the sovereign application ecosystem.", category: "Dev" },
  { id: "Neww", name: "System Update Relay", description: "Centralized notification for new software updates.", category: "Dev" },
  { id: "Omniapi", name: "Universal API Bridge", description: "Inter-node communication for heterogeneous systems.", category: "Dev" },
  { id: "Openapi", name: "API Documentation Sanctum", description: "Source of truth for all integrated service documentation.", category: "Dev" },
  { id: "Pic-Editor", name: "Visual Studio Node", description: "AI-enhanced image editing and manipulation.", category: "AI" },
  { id: "Picgenai", name: "3D Image Forge", description: "High-fidelity 3D and 2D asset generation.", category: "AI" },
  { id: "Projectatlas", name: "Project Atlas", description: "Global mapping of financial and compute power.", category: "AI" },
  { id: "Quantumbank", name: "Quantum Banking Node", description: "Next-gen banking using quantum-resistant logic.", category: "Banking" },
  { id: "Remix-Eth", name: "Smart Contract Forge", description: "On-chain logic development for Ethereum-compatible chains.", category: "Banking" },
  { id: "Static", name: "Visual Telemetry Node", description: "Static visualization of complex system flows.", category: "Dev" },
  { id: "Test", name: "System Diagnostics", description: "Comprehensive health checks for the OS core.", category: "Security" },
  { id: "Trainn", name: "No-Code AI Studio", description: "Empowering non-technical visionaries with neural logic.", category: "AI" },
  { id: "Transactpro", name: "Atomic Transaction Engine", description: "High-throughput settlement engine for verified entities.", category: "Banking" },
  { id: "Veo", name: "Grounded Response Node", description: "AI responses validated against real-time web grounding.", category: "AI" },
  { id: "Webgenai", name: "Dynamic Web Forge", description: "AI-driven deployment of dynamic web applications.", category: "Dev" },
  { id: "Wf", name: "Workflow Architect", description: "Visual mapping and execution of automated business logic.", category: "Dev" },

  // --- Integrated Applications ---
  { id: 'app-github_audit_sync_agent', name: 'Github Audit Sync Agent', description: 'Synchronize and audit GitHub repositories.', category: 'Dev' },
  { id: 'app-b2b_routing_number_resolver', name: 'B2B Routing Number Resolver', description: 'Resolve and verify B2B routing numbers.', category: 'Banking' },
  { id: 'app-citi_account_excel_parser', name: 'Citi Account Excel Parser', description: 'Parse and ingest Citi account statements from Excel.', category: 'Banking' },
  { id: 'app-balance_transfer_analytics_dashboard', name: 'Balance Transfer Analytics', description: 'Analytics and reporting for balance transfers.', category: 'Banking' },
  { id: 'app-card_lifecycle_compliance_checker', name: 'Card Lifecycle Compliance', description: 'Check compliance across card lifecycles.', category: 'Security' },
  { id: 'app-broker_compliance_trade_auditor', name: 'Broker Compliance Trade Auditor', description: 'Audit broker trades for regulatory compliance.', category: 'Security' },
  { id: 'app-military_fund_allocator', name: 'Military Fund Allocator', description: 'Allocate and track military funding.', category: 'Banking' },
  { id: 'app-camt053_statement_parser', name: 'CAMT053 Statement Parser', description: 'Parse ISO 20022 CAMT.053 bank-to-customer statements.', category: 'Banking' },
  { id: 'app-camt053_balance_reconciler', name: 'CAMT053 Balance Reconciler', description: 'Reconcile bank balances using CAMT.053 files.', category: 'Banking' },
  { id: 'app-b2b_cash_flow_stress_tester', name: 'B2B Cash Flow Stress Tester', description: 'Stress test corporate cash flows under macro scenarios.', category: 'Banking' },
  { id: 'app-balance_transfer_compliance_auditor', name: 'Balance Transfer Compliance Auditor', description: 'Audit balance transfers for compliance.', category: 'Security' },
  { id: 'app-card_spend_limit_manager', name: 'Card Spend Limit Manager', description: 'Manage and enforce card spending limits.', category: 'Banking' },
  { id: 'app-financial_regulatory_guardrail', name: 'Financial Regulatory Guardrail', description: 'Enforce regulatory guardrails on transactions.', category: 'Security' },
  { id: 'app-citi_account_kyc_risk_profiler', name: 'Citi Account KYC Risk Profiler', description: 'Profile KYC risk for Citi accounts.', category: 'Security' },
  { id: 'app-statement_reconciliation_portal', name: 'Statement Reconciliation Portal', description: 'Reconcile bank statements with internal ledgers.', category: 'Banking' },
  { id: 'app-citi_account_anomaly_detector', name: 'Citi Account Anomaly Detector', description: 'Detect anomalies in Citi account transactions.', category: 'AI' },
  { id: 'app-card_listing_mock_server', name: 'Card Listing Mock Server', description: 'Mock server for card listing APIs.', category: 'Dev' },
  { id: 'app-multi_currency_balance_consolidator', name: 'Multi Currency Balance Consolidator', description: 'Consolidate balances across multiple currencies.', category: 'Banking' },
  { id: 'app-card_pin_hasher_validator', name: 'Card PIN Hasher Validator', description: 'Securely hash and validate card PINs.', category: 'Security' },
  { id: 'app-b2b_audit_trail_generator', name: 'B2B Audit Trail Generator', description: 'Generate immutable audit trails for B2B transactions.', category: 'Security' },
  { id: 'app-credit_limit_utilization_monitor', name: 'Credit Limit Utilization Monitor', description: 'Monitor credit limit utilization in real-time.', category: 'Banking' },
  { id: 'app-financial_statement_verifier', name: 'Financial Statement Verifier', description: 'Verify financial statements using AI.', category: 'AI' },
  { id: 'app-card_outstanding_balance_tracker', name: 'Card Outstanding Balance Tracker', description: 'Track outstanding balances on corporate cards.', category: 'Banking' },
  { id: 'app-broker_order_execution_simulator', name: 'Broker Order Execution Simulator', description: 'Simulate order execution across brokers.', category: 'Dev' },
  { id: 'app-pqc_crypto_bridge_simulator', name: 'PQC Crypto Bridge Simulator', description: 'Simulate post-quantum cryptographic bridges.', category: 'Security' },
  { id: 'app-election_integrity_dashboard', name: 'Election Integrity Dashboard', description: 'Monitor and verify election registration integrity.', category: 'Security' },
  { id: 'app-balance_transfer_disbursement_orchestrator', name: 'Balance Transfer Disbursement Orchestrator', description: 'Orchestrate disbursements for balance transfers.', category: 'Banking' },
  { id: 'app-cvv_decryption_mock_service', name: 'CVV Decryption Mock Service', description: 'Mock service for CVV decryption.', category: 'Dev' },
  { id: 'app-balance_transfer_interest_simulator', name: 'Balance Transfer Interest Simulator', description: 'Simulate interest accrual on balance transfers.', category: 'Banking' },
  { id: 'app-camt053_mock_generator', name: 'CAMT053 Mock Generator', description: 'Generate mock CAMT.053 statement files.', category: 'Dev' },
  { id: 'app-schema_catalog_custom_registry', name: 'Schema Catalog Custom Registry', description: 'Custom registry for API schema catalogs.', category: 'Dev' },
  { id: 'app-credit_card_simulator', name: 'Credit Card Simulator', description: 'Simulate credit card transactions and lifecycles.', category: 'Dev' },
  { id: 'app-card_tokenization_service', name: 'Card Tokenization Service', description: 'Tokenize sensitive card data.', category: 'Security' },
  { id: 'app-schema_conformance_audit_tool', name: 'Schema Conformance Audit Tool', description: 'Audit API responses for schema conformance.', category: 'Dev' },
  { id: 'app-voter_registration_portal', name: 'Voter Registration Portal', description: 'Portal for voter registration verification.', category: 'Security' },
  { id: 'app-camt053_transaction_exporter', name: 'CAMT053 Transaction Exporter', description: 'Export transactions to CAMT.053 format.', category: 'Banking' },
  { id: 'app-service_principal_provisioner', name: 'Service Principal Provisioner', description: 'Provision and manage Azure service principals.', category: 'Dev' },
  { id: 'app-schema_catalog_search_engine', name: 'Schema Catalog Search Engine', description: 'Search and discover API schemas.', category: 'Dev' },
  { id: 'app-account_summary_mock_service', name: 'Account Summary Mock Service', description: 'Mock service for account summaries.', category: 'Dev' },
  { id: 'app-azure_ad_app_auditor', name: 'Azure AD App Auditor', description: 'Audit Azure AD applications and permissions.', category: 'Security' },
  { id: 'app-schema_validator_orchestrator', name: 'Schema Validator Orchestrator', description: 'Orchestrate schema validation across services.', category: 'Dev' },
  { id: 'app-cross_cloud_federation_manager', name: 'Cross Cloud Federation Manager', description: 'Manage identity federation across clouds.', category: 'Security' },
  { id: 'app-card_function_access_controller', name: 'Card Function Access Controller', description: 'Control access to card functions.', category: 'Security' },
  { id: 'app-api_response_conformance_validator', name: 'API Response Conformance Validator', description: 'Validate API response conformance.', category: 'Dev' },
  { id: 'app-balance_transfer_batch_scheduler', name: 'Balance Transfer Batch Scheduler', description: 'Schedule batches for balance transfers.', category: 'Banking' },
  { id: 'app-balance_transfer_calculator', name: 'Balance Transfer Calculator', description: 'Calculate savings and terms for balance transfers.', category: 'Banking' },
  { id: 'app-card_test_suite_conformance_analyzer', name: 'Card Test Suite Conformance Analyzer', description: 'Analyze card test suite conformance.', category: 'Dev' },
  { id: 'app-api_test_runner', name: 'API Test Runner', description: 'Run automated API conformance tests.', category: 'Dev' },
  { id: 'app-b2b_portfolio_wealth_analyzer', name: 'B2B Portfolio Wealth Analyzer', description: 'Analyze wealth and portfolios for B2B clients.', category: 'Banking' },
  { id: 'app-citi_account_interest_accrual_simulator', name: 'Citi Account Interest Accrual Simulator', description: 'Simulate interest accrual on Citi accounts.', category: 'Banking' },
  { id: 'app-b2b_transaction_categorizer', name: 'B2B Transaction Categorizer', description: 'Categorize B2B transactions using AI.', category: 'AI' },
  { id: 'app-b2b_routing_decryptor_validator', name: 'B2B Routing Decryptor Validator', description: 'Decrypt and validate B2B routing numbers.', category: 'Security' },
  { id: 'app-audit_compliance_tracker', name: 'Audit Compliance Tracker', description: 'Track compliance audits and status.', category: 'Security' },
  { id: 'app-fedramp_compliance_monitor', name: 'FedRAMP Compliance Monitor', description: 'Monitor FedRAMP compliance status.', category: 'Security' },
  { id: 'app-card_merchant_category_classifier', name: 'Card Merchant Category Classifier', description: 'Classify card merchants using AI.', category: 'AI' },
  { id: 'app-balance_transfer_lead_generator', name: 'Balance Transfer Lead Generator', description: 'Generate leads for balance transfers.', category: 'AI' },
  { id: 'app-b2b_interest_rate_optimizer', name: 'B2B Interest Rate Optimizer', description: 'Optimize interest rates for B2B loans.', category: 'Banking' },
  { id: 'app-app_consent_analyzer', name: 'App Consent Analyzer', description: 'Analyze application consent and permissions.', category: 'Security' },
  { id: 'app-b2b_corporate_liquidity_forecaster', name: 'B2B Corporate Liquidity Forecaster', description: 'Forecast corporate liquidity.', category: 'Banking' },
  { id: 'app-card_activation_simulator', name: 'Card Activation Simulator', description: 'Simulate card activation flows.', category: 'Dev' },
  { id: 'app-credit_risk_analyzer', name: 'Credit Risk Analyzer', description: 'Analyze credit risk using AI.', category: 'AI' },
  { id: 'app-balance_transfer_eligibility_checker', name: 'Balance Transfer Eligibility Checker', description: 'Check eligibility for balance transfers.', category: 'Banking' },
  { id: 'app-treasury_reconciliation_engine', name: 'Treasury Reconciliation Engine', description: 'Reconcile treasury accounts.', category: 'Banking' },
  { id: 'app-citiconnect_integration_gateway', name: 'CitiConnect Integration Gateway', description: 'Integrate with CitiConnect APIs.', category: 'Banking' },
  { id: 'app-citizenship_verification_gateway', name: 'Citizenship Verification Gateway', description: 'Verify citizenship status.', category: 'Security' },
  { id: 'app-supplementary_card_orchestrator', name: 'Supplementary Card Orchestrator', description: 'Orchestrate supplementary card issuance.', category: 'Banking' }
];

export const banks = [
  { name: 'Chase', logo: <ShieldCheck size={24} className="text-blue-800" />, institution_id: 'ins_2' },
  { name: 'Bank of America', logo: <Target size={24} className="text-red-600" />, institution_id: 'ins_3' },
  { name: 'Wells Fargo', logo: <Zap size={24} className="text-yellow-600" />, institution_id: 'ins_4' },
];

export const ALL_FEATURES: Feature[] = [
  { id: 'feat_1', name: 'Neural Predictor', icon: '🧠', category: 'Intel', description: 'Real-time market forecasting' },
  { id: 'feat_2', name: 'Quantum Shield', icon: '🛡️', category: 'Vault', description: 'Advanced cryptographic protection' },
  { id: 'feat_3', name: 'Liquidity Bridge', icon: '🌉', category: 'Flow', description: 'Atomic cross-chain swaps' },
  { id: 'feat_4', name: 'Protocol Forge', icon: '🔨', category: 'Forge', description: 'Custom smart contract generation' },
  { id: 'feat_5', name: 'Sovereign ID', icon: '🆔', category: 'Core', description: 'Hardware-bound identity' },
  { id: 'feat_6', name: 'Data Mesh', icon: '🕸️', category: 'Mesh', description: 'Institutional data integration' },
];

export type SlotCategory = 'Core' | 'Intel' | 'Vault' | 'Flow' | 'Mesh' | 'Forge';
export const SLOTS: SlotCategory[] = ['Core', 'Intel', 'Vault', 'Flow', 'Mesh', 'Forge'];

export const AI_MODULES = [
  "https://admin08077-openapi.hf.space",
  "https://admin08077-ai-banking-sovereign.static.hf.space",
  "https://admin08077-aibanke.static.hf.space",
  "https://admin08077-citibank-demo-business-inc-ai-ban-king-demo.static.hf.space",
  "https://admin08077-1233.static.hf.space",
  "https://admin08077-inventions.static.hf.space",
  "https://admin08077-gemini-app-citibank-demo-business-inc-google.static.hf.space",
  "https://admin08077-aibankdemo2.static.hf.space",
  "https://admin08077-airenderer.static.hf.space",
  "https://admin08077-book.static.hf.space",
  "https://admin08077-merrychristmas.static.hf.space",
  "https://admin08077-apiai.static.hf.space",
  "https://admin08077-projectatlas.static.hf.space",
  "https://admin08077-jocall3.static.hf.space",
  "https://admin08077-demob.static.hf.space",
  "https://admin08077-aibanke.static.hf.space",
  "https://admin08077-ai-banking-sovereign.static.hf.space",
  "https://admin08077-static.static.hf.space",
  "https://admin08077-demoo.static.hf.space",
  "https://admin08077-webgenai.static.hf.space",
  "https://admin08077-aiab.static.hf.space",
  "https://admin08077-citibank-demo-business-inc-app.static.hf.space",
  "https://admin08077-aib8nking.static.hf.space",
  "https://admin08077-bb.static.hf.space",
  "https://admin08077-citibank-demo-business-inc-apps.static.hf.space",
  "https://admin08077-newwa.static.hf.space",
  "https://admin08077-jamesocallaghanprivatebank.hf.space",
  "https://admin08077-drip-faucet.static.hf.space",
  "https://admin08077-transactpro.hf.space",
  "https://admin08077-quantumbank.hf.space",
  "https://admin08077-test.hf.space"
];